using System.Globalization;
using System.Text;

namespace Relay.Worker;

/// <summary>
/// The one worker task in this build: read the project's note copies through the broker and
/// write a deterministic summary to <c>out/summary.md</c>. No model, no network, no direct I/O.
/// </summary>
public static class SummarizeTask
{
    private sealed record Note(string Path, string Type, string Status, string Created, string Body);

    public static async Task<(string Summary, IReadOnlyList<string> Outputs)> RunAsync(RunSpecMessage spec, BrokerClient broker)
    {
        await broker.LogAsync($"Listing {spec.Inputs.Count} input file(s)").ConfigureAwait(false);
        var listing = await broker.CallAsync("list_dir", ("path", "inputs")).ConfigureAwait(false);
        var files = listing.Split('\n', StringSplitOptions.RemoveEmptyEntries | StringSplitOptions.TrimEntries).Where(f => f.EndsWith(".md", StringComparison.OrdinalIgnoreCase)).ToList();

        var notes = new List<Note>();
        foreach (var file in files)
        {
            var text = await broker.CallAsync("read_file", ("path", file)).ConfigureAwait(false);
            notes.Add(Parse(file, text));
        }
        await broker.LogAsync($"Read {notes.Count} note(s); composing summary").ConfigureAwait(false);

        var content = Render(spec, notes);
        const string output = "out/summary.md";
        await broker.CallAsync("write_file", ("path", output), ("text", content)).ConfigureAwait(false);

        var byType = notes.Where(n => n.Status != "superseded").GroupBy(n => n.Type).ToDictionary(g => g.Key, g => g.Count());
        var summary = $"Summarized {notes.Count} note(s): {Count(byType, "decision")} decision(s), {Count(byType, "task")} task(s), {Count(byType, "question")} question(s)";
        return (summary, [output]);
    }

    private static int Count(Dictionary<string, int> byType, string type) => byType.GetValueOrDefault(type);

    private static Note Parse(string path, string text)
    {
        var type = "note"; var status = "active"; var created = "";
        var body = text;
        var lines = text.Replace("\r\n", "\n").Split('\n');
        if (lines.Length > 0 && lines[0].Trim() == "---")
        {
            var end = Array.FindIndex(lines, 1, l => l.Trim() == "---");
            if (end > 0)
            {
                foreach (var line in lines[1..end])
                {
                    var colon = line.IndexOf(':', StringComparison.Ordinal);
                    if (colon <= 0) continue;
                    var key = line[..colon].Trim();
                    var value = line[(colon + 1)..].Trim().Trim('"');
                    switch (key)
                    {
                        case "type": type = value; break;
                        case "status": status = value; break;
                        case "created": created = value; break;
                    }
                }
                body = string.Join('\n', lines[(end + 1)..]).Trim();
            }
        }
        return new Note(path, type, status, created, body);
    }

    private static string Render(RunSpecMessage spec, List<Note> notes)
    {
        var sb = new StringBuilder();
        sb.Append("# Summary of ").Append(spec.ProjectSlug).Append('\n').Append('\n');
        sb.Append("Generated by worker run ").Append(spec.RunId).Append(" (task: ").Append(spec.Task).Append(") from ").Append(notes.Count).Append(" note(s). ");
        sb.Append("Derived content: every line below points at a source file in the Sources section; nothing here is a canonical note.\n\n");

        foreach (var (type, heading) in new[] { ("decision", "Decisions"), ("task", "Tasks"), ("question", "Open questions"), ("idea", "Ideas"), ("fact", "Facts"), ("reference", "References") })
        {
            var group = notes.Where(n => n.Type == type && n.Status != "superseded").OrderBy(n => n.Created, StringComparer.Ordinal).ToList();
            if (group.Count == 0) continue;
            sb.Append("## ").Append(heading).Append(" (").Append(group.Count).Append(")\n\n");
            foreach (var n in group)
            {
                sb.Append("- ").Append(FirstLine(n.Body));
                if (n.Status == "disputed") sb.Append(" _(disputed)_");
                if (n.Created.Length >= 10) sb.Append("  — ").Append(n.Created[..10]);
                sb.Append('\n');
            }
            sb.Append('\n');
        }
        var superseded = notes.Count(n => n.Status == "superseded");
        if (superseded > 0) sb.Append("_").Append(superseded).Append(" superseded note(s) were read but left out of the lists above._\n\n");

        sb.Append("## Sources\n\n");
        foreach (var n in notes.OrderBy(n => n.Path, StringComparer.Ordinal)) sb.Append("- ").Append(n.Path).Append('\n');
        return sb.ToString();
    }

    private static string FirstLine(string body)
    {
        var line = body.Split('\n').FirstOrDefault(l => l.Trim().Length > 0)?.Trim() ?? "(empty)";
        return line.Length > 200 ? line[..197] + "…" : line;
    }
}
